name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7
        with:
          install: true

      - name: Read content of Pharo-sync-commit file and set its 3rd line to environment variable (ignoring comments)
      run: |
        # Read the content of the second line of the file and store it in SHA_OR_BRANCH
        SHA_OR_BRANCH=$(sed -n '3p' Pharo-sync-commit)
        echo "SHA_OR_BRANCH=$SHA_OR_BRANCH" >> $GITHUB_ENV
      working-directory: ${{ github.workspace }}


      - name: Build Docker image and store in cache
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: false
          load: true
          tags: exercism/pharo-smalltalk-test-runner
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SHA_OR_BRANCH=${{ env.SHA_OR_BRANCH }}

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
